GPUS: "0,1,2,3"
DATALOADER_WORKERS: 32
BATCH_SIZE: 32
MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001  

END_EPOCH: 50
LOAD_ONLY_PRETRAINED_BACKBONE: True
LOAD_PRETRAINED_MODEL: True
PRETRAINED_MODEL_PATH: 'snapshot/model.pth'

LOG_DIR: 'logs'
LOG_PRINT_FREQ: 10
CHECKPOINT_DIR: 'snapshot'
CHECKPOINT_SAVE_FREQ: 1

LEARNING_RATE:
  LR_POLICY: 'log'
  START_LR: 0.005
  END_LR: 0.00001
  FREEZE_BACKBONE: True
  BACKBONE_UNFREEZE_EPOCH: 6
  WARMUP:
    ENABLE: True
    LR_POLICY: 'log'
    EPOCH: 5
    START_LR: 0.001
    END_LR: 0.005