GPUS: "0,1,2,3"
DATALOADER_WORKERS: 32
BATCH_SIZE: 32
MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001  

END_EPOCH: 50
LOAD_ONLY_PRETRAINED_BACKBONE: True
FREEZE_BACKBONE: True
BACKBONE_UNFREEZE_EPOCH: 6
LOAD_PRETRAINED_MODEL: False
PRETRAINED_MODEL_PATH: 'snapshot/model.pth'

LOG_DIR: 'logs'
LOG_PRINT_FREQ: 10
TENSORBOARD_DIR: 'tensorboard'
CHECKPOINT_DIR: 'snapshot'
CHECKPOINT_SAVE_FREQ: 1

LEARNING_RATE:
  LR_POLICY: 'log'
  START_LR: 0.005
  END_LR: 0.00001
  WARMUP:
    ENABLE: True
    LR_POLICY: 'log'
    EPOCH: 5
    START_LR: 0.001
    END_LR: 0.005

DATASETS:
  GTA_EVENTS_DATASET:
    PATH: 'D:\furkan\GTA_Events_Dataset'
    TRAIN_TXT: 'D:\furkan\GTA_Events_Dataset\train_videos.txt'
    TEST_TXT: 'D:\furkan\GTA_Events_Dataset\test_videos.txt'

AUGMENTATION:
  COLOR: 1
  FLIP: 0
  ROTATION: 0
  GRAY: 0
  BLUR: 0
